expression ::=
  sum_sub
  "==>> expression(SumSub)";

sum_sub ::=
  product_div {("+"|"-") product_div "==>> product_div_repetition(Sign, ProductDiv)"}
  "==>> sum_sub(_, ProductDivRepetition)";

product_div ::=
  ["+"|"-"] term {("*"|"/") term "==>> term_repetition(Sign, Term)"}
  "==>> product_div(_, NumberOrExpression, TermRepetition)";

term ::=
  number
  "==>> term(Number)" |
  "(" expression ")"
  "==>> term(_, Expression, _)";

<number> ::=
  "(\+|\-)?[0-9]+(\.[0-9]+)?";
